name: Conventional Commits

on:
  pull_request:
  push:
    branches: [ develop, feature-precommit ]

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: webiny/action-conventional-commits@v1.1.0
